name: &name "GlowTTS"
sample_rate: &sr 22050
n_fft: &n_fft 1024
n_mels: &n_mels 80
fmax: &fmax null
n_stride: &n_window_stride 256
pad_value: &pad_value -11.52

model:
  mel_channels: *n_mels
  hidden_channels: 192
  filter_channels: 768
  filter_channels_dp: 256
  kernel_size: 3
  p_dropout: 0.1
  n_blocks_dec: 12
  n_layers_enc: 6
  n_heads: 2
  p_dropout_dec: 0.05
  dilation_rate: 1
  kernel_size_dec: 5
  n_block_layers: 4
  n_sqz: 2
  n_split: 4
  sigmoid_scale: false
  prenet: true
  mean_only: true
  hidden_channels_enc: 192
  hidden_channels_dec: 192
  window_size: 4

  train_ds:
    manifest_filepath: /home/samuel/Data/ljspeech/filelists/nvidia_ljspeech_train.json
    sample_rate: *sr
    batch_size: 8
    trim_silence: True
    max_duration: 16.7
    shuffle: True
    num_workers: 8
    cmu_dict_path: /home/samuel/Data/cmudict/cmu_dictionary
    augmentor:
      shift:
        prob: 0.3
        min_shift_ms: -5.0
        max_shift_ms: 5.0
      white_noise:
        prob: 0.3
        min_level: -90
        max_level: -46


  validation_ds:
    manifest_filepath: /home/samuel/Data/ljspeech/filelists/nvidia_ljspeech_val.json
    sample_rate: *sr
    batch_size: 8
    trim_silence: True
    max_duration: 16.7
    shuffle: False
    num_workers: 8
    cmu_dict_path: /home/samuel/Data/cmudict/cmu_dictionary

  preprocessor:
    cls: nemo.collections.asr.parts.features.FilterbankFeatures
    params:
      dither: 0.0
      nfilt: *n_mels
      frame_splicing: 1
      highfreq: *fmax
      log: true
      log_zero_guard_type: clamp
      log_zero_guard_value: 1e-05
      lowfreq: 0
      mag_power: 1.0
      n_fft: *n_fft
      n_window_size: 1024
      n_window_stride: *n_window_stride
      normalize: null
      pad_to: 16
      pad_value: *pad_value
      preemph: null
      sample_rate: *sr
      stft_conv: true
      window: hann

  spec_augment:
    cls: nemo.collections.asr.modules.SpectrogramAugmentation
    params:
      rect_freq: 50
      rect_masks: 5
      rect_time: 120


  optim:
    name: adam
    lr: 1e-3
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 0

    # scheduler setup
    sched:
      name: CosineAnnealing

      # pytorch lightning args
      # monitor: val_loss
      # reduce_on_plateau: false

      # Scheduler params
      warmup_steps: 4000
      min_lr: 1e-5
      last_epoch: -1

trainer:
  gpus: -1 # number of gpus
  max_epochs: 500
  max_steps: 20000
  num_nodes: 1
  distributed_backend: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager

exp_manager:
  root_dir: null
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
